import { ProjectCardProps } from "@/components/project-card"

export const projects: ProjectCardProps[] = [
  {
    name: "Quinvo",
    subtitle: "Simplified invoicing for French entrepreneurs",
    description: "",
    live: "https://quinvo-app.vercel.app",
    link: "/projects/quinvo",
    github: "https://github.com/julien7518/quinvo",
    categories: ["SaaS", "UI/UX", "React"],
    imageAlt: "Screenshot of the Quinvo user dashboard",
  },
  {
    name: "Mellow",
    subtitle: "Beautiful, smooth, always-on-top music player for macOS",
    description: "",
    link: "/projects/mellow",
    github: "https://github.com/julien7518/mellow",
    categories: ["UI/UX", "Swift"],
    imageAlt: "Screenshot of the Mellow player in action",
  },
  {
    name: "ShaderLab",
    subtitle: "A real-time 3D editor using WebGPU",
    description: "",
    link: "/projects/shaderlab",
    github: "https://github.com/julien7518/shaderlab",
    live: "https://webgpu-shaderlab.vercel.app",
    imageAlt: "Screenshot of the project",
  },
  {
    name: "PaperLM",
    subtitle: "A privacy-first AI research assistant that runs in your browser",
    description: "",
    live: "https://paperlm.vercel.app",
    github: "https://github.com/julien7518/paperlm",
    categories: ["AI", "React"],
    imageAlt: "Screenshot of the PaperLM interface",
  },
  {
    name: "MNISTify",
    subtitle: "Real-time handwritten digit recognition, powered by WebGPU",
    description: "",
    link: "/projects/mnistify",
    github: "https://github.com/julien7518/mnistify",
    live: "https://mnistify.vercel.app",
    imageAlt: "Screenshot of a prediction",
  },
  {
    name: "Arno Cauchois",
    subtitle: "Arno Cauchois' portfolio",
    description: "",
    live: "https://arnocauchois.com",
    categories: ["Portfolio"],
    imageAlt: "Screenshot of the portfolio",
  },
  {
    name: "Elsa Fernandes",
    subtitle: "Elsa Fernandes' portfolio",
    description: "",
    live: "https://elsa-fernandes.vercel.app",
    github: "https://github.com/julien7518/elsa-fernandes",
    categories: ["Portfolio"],
    imageAlt: "Screenshot of the home page",
  },
]
